# Generated by Django 5.2.1 on 2025-05-19 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai/')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2025, 5, 19, 9, 19, 25, 505593, tzinfo=datetime.timezone.utc))),
                ('type', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELICHI')], max_length=2)),
            ],
        ),
    ]
