# Generated by Django 5.2.1 on 2025-05-19 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 9, 19, 50, 69973, tzinfo=datetime.timezone.utc)),
        ),
    ]
